services:
  - type: web
    name: buildmate-api
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 9292
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_URLS
        value: http://localhost:5173,http://127.0.0.1:5173,https://buildmate-steel.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: MAIL_FROM_EMAIL
        value: tharunreddyb30@gmail.com
      - key: MAIL_FROM_NAME
        value: Tharun from BuildMate
      - key: MAIL_ENABLED
        value: "true"
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=65 -XX:InitialRAMPercentage=20
